sm8150-common: Kang system WFD stack from OOS
Solves the dependency issue of libwfddisplayconfig requiring
libdisplayconfig.qti without a clear variant:

  error: vendor/sony/sm8150-common/Android.bp:19355:1: dependency
  "libdisplayconfig.qti" of "libwfddisplayconfig" missing variant:
  os:android,image:,arch:arm64_armv8-2a_cortex-a76,sdk:,link:shared

Signed-off-by: voidanix <voidanix@keyedlimepie.org>